import { useMemo, useState } from "react";
import { listAuditEvents } from "../app/localState";

export function AuditPage() {
  const [query, setQuery] = useState("");
  const events = listAuditEvents();

  const filtered = useMemo(() => {
    const term = query.trim().toLowerCase();
    if (!term) {
      return events;
    }

    return events.filter((event) => {
      return (
        event.type.toLowerCase().includes(term) ||
        event.message.toLowerCase().includes(term) ||
        Object.values(event.metadata ?? {}).some((value) => value.toLowerCase().includes(term))
      );
    });
  }, [events, query]);

  return (
    <section className="page">
      <h2>Audit Log</h2>
      <p className="muted">
        Backend audit API is not available yet. This page currently displays client-side events generated by uploads,
        check starts, and results fetches.
      </p>

      <section className="panel">
        <label>
          Search events
          <input
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="type, message, metadata"
          />
        </label>
      </section>

      <section className="panel">
        <h3>Event Timeline</h3>
        {filtered.length === 0 ? <p className="muted">No audit events found.</p> : null}
        <ul className="timeline">
          {filtered.map((event) => (
            <li key={event.id}>
              <div>
                <strong>{event.type}</strong>
                <p>{event.message}</p>
                <small>{new Date(event.timestamp).toLocaleString()}</small>
              </div>
              {event.metadata ? (
                <pre>{JSON.stringify(event.metadata, null, 2)}</pre>
              ) : null}
            </li>
          ))}
        </ul>
      </section>
    </section>
  );
}
